version: '3.8'
services:
  lerobot:
    build: .
    volumes:
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Follower arm
      - /dev/ttyUSB1:/dev/ttyUSB1  # Leader arm
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: bash