# Config for follower arm (with dual-servos on some joints, linear gripper)
# Use custom DualFeetechActuator for dual joints in your robot class
# Run `lerobot calibrate lerobot/configs/robot/follower.yaml` to calibrate
# It will move to middle (home), then each joint to min/max limits
# Update scales/offsets from your ROS code as initials

fps: 30

robot_type: custom_feetech_arm.CustomFeetechArm

arms:
  follower:
    bus:
      type: feetech
      port: /dev/ttyUSB0
      baud_rate: 1000000
    default_speed: 500
    actuators:
      base_link_Revolute-1:
        custom_class: DualFeetechActuator  # Not standard; in your CustomFeetechArm __init__, parse and use DualFeetechActuator if 'custom_class' present
        leader_id: 1  # Single, but for consistency; adjust in code to use FeetechActuator if no follower_id
        model: sts3215
        offset_rad: 0.0  # Calibrate updates
        orientation: 1
        scale: 644.9  # From your calibration dict
      link1_Revolute-3:
        custom_class: DualFeetechActuator
        leader_id: 2
        follower_id: 3
        model: sts3215
        offset_rad: 0.0
        orientation: 1
        scale: 651.0  # From calib (651)
      link2_Revolute-4:
        custom_class: DualFeetechActuator
        leader_id: 4
        follower_id: 5
        model: sts3215
        offset_rad: 0.0
        orientation: 1
        scale: 647.2
      link3_Revolute-5:
        custom_class: DualFeetechActuator  # Single, adjust in code
        leader_id: 6
        model: sts3215
        offset_rad: 0.0
        orientation: 1
        scale: 628.0
      link4_Revolute-6:
        custom_class: DualFeetechActuator  # Single
        leader_id: 7
        model: sts3215
        offset_rad: 0.0
        orientation: 1
        scale: 640.0
      link5_Revolute-7:
        custom_class: DualFeetechActuator  # Single
        leader_id: 8
        model: sts3215
        offset_rad: 0.0
        orientation: 1
        scale: 654.0
      link6_Slider-8:
        custom_class: LinearGripperActuator
        id: 9  # For LinearGripperActuator
        model: sts3215
        offset_rad: 0.0  # Here offset in m, but calibrate will handle; initial 0
        orientation: 1
        # Scale not used directly; handled in class

cameras:
  ee_camera:  # End effector camera (RealSense D405)
    type: realsense
    serial_number: 218622275492  # Run `lerobot find-cameras realsense` to get serial; update if multiple devices
    width: 848    
    height: 480
    fps: 30
    enable_color: true  # RGB stream
    enable_depth: true  # Depth stream (disable if not needed for VLA)

calibration: {}