robot:
  name: custom_arm
  class: CustomArmRobot
  kwargs:
    port: "/dev/ttyUSB0"
    is_leader: false  # Toggle for leader/follower
cameras:
  - name: main_camera
    class: LogitechC270
    kwargs:
      index: 0
      width: 640
      height: 480
      fps: 30